### ISSUE TITLE
too many open files

### ISSUE THREAD

**Issue by eamonnmag** [HEPData/hepdata-converter-ws#5]
http://stackoverflow.com/questions/18280612/ioerror-errno-24-too-many-open-files

Happens for http://hepdata.net/record/60092 when downloading ROOT files.
See HTML output here (had to attach as txt file).
I restarted the docker container and now things work again (well the error is about the bin ordering for this record). But there are places in the code where the files are not being closed, this is most probably in the actual converter code though.

[60092-1-root.txt](https://github.com/HEPData/hepdata-converter-ws/files/23999/60092-1-root.txt)

**Comment by kaplun** [comment]
Hi! This is a common Python issue. It happens in https://github.com/HEPData/hepdata-converter-ws/blob/master/hepdata_converter_ws/api.py#L31

where you use `os.mkstemp` but you ignore the open file handle that is returned. So the file stays open until the process terminate. You can use `os.fdopen(handle)` to recover the returned handle and use it as a Pythonic file object, or better use one of the object oriented version of `tempfile` module.

**Comment by eamonnmag** [comment]
Nice, thanks @kaplun!

**Comment by kaplun** [comment]
Is it fixed? :)

**Comment by jstypka** [comment]
Yes, with e36ad6aca3a9a87dd7b36b5e771e0dabce0fb5e5. I just forgot to add the `closes #5` bit to the commit message :)
